### ISSUE TITLE
Wrong homepage URL in pb-falcon package metadata

### ISSUE THREAD

**Issue by peterjc** [PacificBiosciences/pbbioconda#22]
Wrong homepage URL in ``pb-falcon`` package metadata as shown on https://anaconda.org/bioconda/pb-falcon

Currently https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pb-falcon/meta.yaml

```yaml
about:
  home: 'https://github.com/PacificBiosciences/pypeFLOW'
  license: "BSD 3-Clause Clear License"
  summary: "FALCON/Unzip tool-suite (originally by Jason Chin)"
  authors:
  - cschin
  - pb-cdunn
  - isovic
```

I'm unclear what the best URL would be, maybe https://github.com/PacificBiosciences/FALCON or https://pb-falcon.readthedocs.io/ ?
