### ISSUE TITLE
Updating metadata for pbbam package

### ISSUE THREAD

**Issue by peterjc** [PacificBiosciences/pbbioconda#29]
Re: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/pbbam/meta.yaml

```yaml
about:
  home: https://github.com/PacificBiosciences/pbbam
  license: BSD
  summary: PacBio BAM C++ library
```

When installed this says ``BSD 3-Clause Clear License`` rather than just ``BSD``, consistent with https://github.com/PacificBiosciences/pbbam/blob/develop/LICENSE.txt

P.S. Also it would be nice to have a more details description as the about summary, e.g. Copied from https://github.com/PacificBiosciences/pbbam/blob/develop/README.md says:

> The pbbam software package provides components to create, query, & edit PacBio BAM files and associated indices. These components include a core C++ library, bindings for additional languages, and command-line utilities.

e.g. "C++ library and command line tools to create, query, edit and index PacBio BAM files."
